"""Phase 2 discovery and sandbox purchase state

Revision ID: d1b86c024442
Revises: efe55f71222d
Create Date: 2026-09-27 15:30:45.684178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b86c024442'
down_revision: Union[str, Sequence[str], None] = 'efe55f71222d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('baseline_complete', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('next_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('purchase_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('retailers', sa.String(length=300), nullable=False),
    sa.Column('product_types', sa.String(length=500), nullable=False),
    sa.Column('title_include', sa.String(length=300), nullable=False),
    sa.Column('title_exclude', sa.String(length=300), nullable=False),
    sa.Column('max_item_cents', sa.Integer(), nullable=False),
    sa.Column('max_order_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('retailer_direct_only', sa.Boolean(), nullable=False),
    sa.Column('daily_spend_cents', sa.Integer(), nullable=False),
    sa.Column('lifetime_sku_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovered_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('retailer', sa.String(length=100), nullable=False),
    sa.Column('retailer_product_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('seller', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.String(length=40), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('baseline', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['discovery_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer', 'retailer_product_id')
    )
    op.create_index(op.f('ix_discovered_products_source_id'), 'discovered_products', ['source_id'], unique=False)
    op.create_table('purchase_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('reserved_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('provider_status', sa.String(length=50), nullable=True),
    sa.Column('provider_total_cents', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('next_reconcile_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['purchase_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('provider_order_id')
    )
    op.create_index(op.f('ix_purchase_candidates_product_id'), 'purchase_candidates', ['product_id'], unique=False)
    op.create_table('purchase_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['purchase_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_events_candidate_id'), 'purchase_events', ['candidate_id'], unique=False)
    op.create_table('purchase_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['purchase_candidates.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('provider_order_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['purchase_candidates.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id'),
    sa.UniqueConstraint('provider_order_id')
    )
    op.add_column('products', sa.Column('seller', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('price_confirmed', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('products', sa.Column('retailer_product_id', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('observed_title', sa.String(length=200), nullable=True))
    op.add_column('worker_state', sa.Column('purchases_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_state', 'purchases_enabled')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'observed_title')
    op.drop_column('products', 'retailer_product_id')
    op.drop_column('products', 'seller')
    op.drop_column('products', 'price_confirmed')
    op.drop_table('purchase_orders')
    op.drop_table('purchase_attempts')
    op.drop_index(op.f('ix_purchase_events_candidate_id'), table_name='purchase_events')
    op.drop_table('purchase_events')
    op.drop_index(op.f('ix_purchase_candidates_product_id'), table_name='purchase_candidates')
    op.drop_table('purchase_candidates')
    op.drop_index(op.f('ix_discovered_products_source_id'), table_name='discovered_products')
    op.drop_table('discovered_products')
    op.drop_table('purchase_rules')
    op.drop_table('discovery_sources')
    # ### end Alembic commands ###
