"""Initial persistent monitor schema

Revision ID: efe55f71222d
Revises: 
Create Date: 2026-09-27 13:56:06.990990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe55f71222d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('retailer', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_known_status', sa.String(length=30), nullable=True),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('last_successful_check', sa.DateTime(), nullable=True),
    sa.Column('last_status_change', sa.DateTime(), nullable=True),
    sa.Column('last_alert', sa.DateTime(), nullable=True),
    sa.Column('next_check_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('retailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('example_url', sa.Text(), nullable=True),
    sa.Column('in_stock_text', sa.Text(), nullable=True),
    sa.Column('out_of_stock_text', sa.Text(), nullable=True),
    sa.Column('stock_selector', sa.String(length=255), nullable=True),
    sa.Column('price_selector', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('last_cycle_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_checked_at'), 'status_history', ['checked_at'], unique=False)
    op.create_index(op.f('ix_status_history_product_id'), 'status_history', ['product_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('status_history_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['status_history_id'], ['status_history.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_history_id')
    )
    op.create_index(op.f('ix_alert_history_attempted_at'), 'alert_history', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_alert_history_product_id'), 'alert_history', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_history_product_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_attempted_at'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_status_history_product_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_checked_at'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_table('worker_state')
    op.drop_table('retailers')
    op.drop_table('products')
    # ### end Alembic commands ###
